# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: false

# Setup
title:               HM`s blog
tagline:             'Connect everythings'
description:         'HMC softi'
url:                 https://hm4725.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Hyeon min Lee
  url:               https://www.instagram.com/hm_softi/
  email:             4725hmc@gmail.com

# Custom vars
version:             1.0.0

# Plugins
plugins: [jekyll-paginate]

# Category
category_dir: category
